package org.example.youtubeaisummary.service;


import io.github.thoroldvix.api.*;
import org.example.youtubeaisummary.vo.YoutubeVideo;
import org.springframework.stereotype.Service;

import java.util.Optional;
import java.util.stream.StreamSupport;


@Service
public class SubtitleService {
    private final YoutubeTranscriptApi api;

    public SubtitleService(YoutubeTranscriptApi api) {
        this.api = api;
    }

    public String fetchSubs(YoutubeVideo video) {
        String videoId = video.getVideoId();

        try {
            TranscriptList transcriptList = api.listTranscripts(videoId);

            Optional<Transcript> autoGeneratedTranscript = StreamSupport.stream(transcriptList.spliterator(), false)
                    .filter(Transcript::isGenerated)
                    .findFirst();

            if (autoGeneratedTranscript.isEmpty()) {
                throw new RuntimeException("이 영상에는 자동 생성된 자막이 없습니다.");
            }

            TranscriptContent transcriptContent = autoGeneratedTranscript.get().fetch();

            TranscriptFormatter textFormatter = TranscriptFormatters.textFormatter();
            return textFormatter.format(transcriptContent);

        } catch (TranscriptRetrievalException e) {
            throw new RuntimeException("자막을 가져오는 중 오류가 발생했습니다: " + e.getMessage(), e);
        }
    }
}